name: env_evcap
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - blas
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cryptography
  - cudatoolkit
  - faiss-cpu
  - ffmpeg
  - freetype
  - giflib
  - gmp
  - gnutls
  - idna
  - jpeg
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libdeflate
  - libfaiss
  - libffi
  - libgcc-ng
  - libgomp
  - libiconv
  - libidn2
  - libpng
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libunistring
  - libwebp
  - libwebp-base
  - lz4-c
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - nettle
  - numpy
  - numpy-base
  - openh264
  - openjpeg
  - openssl
  - pillow
  - pip
  - pycparser
  - pyopenssl
  - pysocks
  - python
  - pytorch
  - pytorch-mutex
  - readline
  - requests
  - setuptools
  - six
  - sqlite
  - tk
  - torchaudio
  - torchvision
  - urllib3
  - wheel
  - xz
  - yaml
  - zlib
  - zstd
  - pip:
    - accelerate
    - aiofiles
    - aiohttp
    - aiosignal
    - altair
    - antlr4-python3-runtime
    - anyio
    - appdirs
    - argon2-cffi
    - argon2-cffi-bindings
    - arrow
    - asttokens
    - async-lru
    - async-timeout
    - attrs
    - babel
    - backcall
    - beautifulsoup4
    - bitsandbytes
    - bleach
    - blis
    - braceexpand
    - catalogue
    - cchardet
    - chardet
    - click
    - comm
    - confection
    - contourpy
    - cycler
    - cymem
    - datasets
    - debugpy
    - decorator
    - decord
    - defusedxml
    - diffusers
    - dill
    - docker-pycreds
    - einops
    - exceptiongroup
    - executing
    - fairscale
    - fastapi
    - fastjsonschema
    - ffmpy
    - filelock
    - fonttools
    - fqdn
    - frozenlist
    - fsspec
    - gitdb
    - gitpython
    - gradio
    - gradio-client
    - h11
    - httpcore
    - httpx
    - huggingface
    - huggingface-hub
    - imageio
    - importlib-metadata
    - importlib-resources
    - intel-openmp
    - iopath
    - ipdb
    - ipykernel
    - ipython
    - isoduration
    - jedi
    - jinja2
    - joblib
    - json5
    - jsonpointer
    - jsonschema
    - jsonschema-specifications
    - jupyter-client
    - jupyter-core
    - jupyter-events
    - jupyter-lsp
    - jupyter-server
    - jupyter-server-terminals
    - jupyterlab
    - jupyterlab-pygments
    - jupyterlab-server
    - kiwisolver
    - langcodes
    - lazy-loader
    - linkify-it-py
    - llvmlite
    - markdown-it-py
    - markupsafe
    - matplotlib
    - matplotlib-inline
    - mdit-py-plugins
    - mdurl
    - mistune
    - mkl
    - mpmath
    - multidict
    - multiprocess
    - murmurhash
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - networkx
    - nltk
    - notebook
    - notebook-shim
    - numba
    - nvidia-cublas-cu12
    - nvidia-cuda-cupti-cu12
    - nvidia-cuda-nvrtc-cu12
    - nvidia-cuda-runtime-cu12
    - nvidia-cudnn-cu12
    - nvidia-cufft-cu12
    - nvidia-curand-cu12
    - nvidia-cusolver-cu12
    - nvidia-cusparse-cu12
    - nvidia-nccl-cu12
    - nvidia-nvjitlink-cu12
    - nvidia-nvtx-cu12
    - omegaconf
    - openai
    - opencv-python
    - orjson
    - overrides
    - packaging
    - pandas
    - pandocfilters
    - parso
    - pathtools
    - pathy
    - peft
    - pexpect
    - pickleshare
    - platformdirs
    - portalocker
    - preshed
    - prometheus-client
    - prompt-toolkit
    - protobuf
    - psutil
    - ptyprocess
    - pure-eval
    - pyarrow
    - pycocoevalcap
    - pycocotools
    - pydantic
    - pydub
    - pygments
    - pynndescent
    - pyparsing
    - python-dateutil
    - python-json-logger
    - python-multipart
    - pytz
    - pyyaml
    - pyzmq
    - referencing
    - regex
    - rfc3339-validator
    - rfc3986-validator
    - rpds-py
    - safetensors
    - scikit-image
    - scikit-learn
    - scipy
    - semantic-version
    - send2trash
    - sentence-transformers
    - sentencepiece
    - sentry-sdk
    - setproctitle
    - smart-open
    - smmap
    - sniffio
    - soupsieve
    - spacy
    - spacy-legacy
    - spacy-loggers
    - srsly
    - stack-data
    - starlette
    - sympy
    - tbb
    - tenacity
    - terminado
    - thinc
    - threadpoolctl
    - tifffile
    - timm
    - tinycss2
    - tokenizers
    - tomli
    - toolz
    - torch
    - tornado
    - tqdm
    - traitlets
    - transformers
    - triton
    - typer
    - types-python-dateutil
    - typing-extensions
    - tzdata
    - uc-micro-py
    - umap-learn
    - uri-template
    - uvicorn
    - wandb
    - wasabi
    - wcwidth
    - webcolors
    - webdataset
    - webencodings
    - websocket-client
    - websockets
    - xxhash
    - yarl
    - zipp
